#pragma once

#define LAUNCHER_VERSION_COMPATIBLE  2
#define LAUNCHER_VERSION_FEATURE     2
#define LAUNCHER_VERSION_PATCH       0

#define LAUNCHER_VERSION_STRINGIFY(compatible, feature, patch) #compatible"."#feature"."#patch
#define LAUNCHER_VERSION_TOSTRING(compatible, feature, patch) LAUNCHER_VERSION_STRINGIFY(compatible,feature,patch)
#define LAUNCHER_VERSION_STRING LAUNCHER_VERSION_TOSTRING( LAUNCHER_VERSION_COMPATIBLE, LAUNCHER_VERSION_FEATURE, LAUNCHER_VERSION_PATCH)

#define RESOURCE_VERSION_STRINGIFY(compatible, feature, patch) #compatible", "#feature", "#patch", 0"
#define RESOURCE_VERSION_TOSTRING(compatible, feature, patch) RESOURCE_VERSION_STRINGIFY(compatible, feature, patch)
#define RESOURCE_VERSION_STRING RESOURCE_VERSION_TOSTRING(LAUNCHER_VERSION_COMPATIBLE,LAUNCHER_VERSION_FEATURE,LAUNCHER_VERSION_PATCH)
